### ISSUE TITLE
Optimize ci process

### ISSUE THREAD

**Issue by lqxhub** [OpenAtomFoundation/pikiwidb-raft#65]
现在的CI流程是先编译代码, 然后再去检查代码格式

https://github.com/OpenAtomFoundation/pikiwidb/blob/unstable/.github/workflows/pikiwidb.yml#L19

```yaml
      - name: Build
        run: |
          sh build.sh

      - name: Check Format
        working-directory: ${{ github.workspace }}/build
        run: |
          make check-format

```

我感觉可以优化一下, 先做代码检查,再去编译, 如果代码格式有问题,可以不用去编译了,减少CI等待时间

format依赖 cmake 生成的 MakeFile,
这里需要修改一下 `build.sh` 脚本, 先生成 `MakeFile` 但是不编译代码
